name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Authenticate with GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Step 3: Set the GCP Project
      - name: Set GCP Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT }}

      # Step 4: Configure Docker for Artifact Registry (or GCR)
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      # Step 5: Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/flask-app:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/flask-app:${{ github.sha }}

      # Step 6: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-app \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/flask-app:${{ github.sha }} \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
