name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Authenticate with GCP
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # Set up the GCP project
    - name: Set up GCP project
      run: gcloud config set project ${{ secrets.GCP_PROJECT }}
      
    # Debug: Output project for confirmation
    - name: Debug Project
      run: echo "GCP Project: ${{ secrets.GCP_PROJECT }}"

    # Build Docker image
    - name: Build and push Docker image
      run: |
        # Configure Docker to use GCP's Artifact Registry
        gcloud auth configure-docker "${{ secrets.GCP_REGION }}-docker.pkg.dev"
        
        # Build Docker image and tag it
        docker build -t "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cloud-run/flask-app:${{ github.sha }}" .
        
        # Push Docker image to Artifact Registry
        docker push "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cloud-run/flask-app:${{ github.sha }}"

    # Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy flask-app \
          --image "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cloud-run/flask-app:${{ github.sha }}" \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
